# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mae', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mae',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='mae',
            name='logradouro',
        ),
        migrations.AddField(
            model_name='mae',
            name='animal_estimacao',
            field=models.CharField(choices=[('C', 'Cachorro'), ('G', 'Gato'), ('P', 'Passaro')], default=1, max_length=1, verbose_name='Animais de estimação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mae',
            name='nome',
            field=models.CharField(max_length=250, verbose_name='Nome completo'),
        ),
    ]
