# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mae', '0003_auto_20170527_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApoioMae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Criado em')),
                ('data_inicio', models.DateTimeField(verbose_name='Data inicio')),
                ('data_fim', models.DateTimeField(verbose_name='Data final')),
                ('foi_processado', models.BooleanField(verbose_name='Foi processado?')),
                ('qtd_horas', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de horas')),
                ('valor_hora', models.IntegerField(blank=True, null=True, verbose_name='Valor hora')),
            ],
        ),
        migrations.CreateModel(
            name='ApoioMaeFilhos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apoio_mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mae.ApoioMae')),
                ('filho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mae.Filho')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoMae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Criado em')),
                ('avaliacao', models.IntegerField(blank=True, null=True, verbose_name='Avaliacao')),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioMae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Criado em')),
                ('comentario', models.TextField(verbose_name='Comentario')),
            ],
        ),
        migrations.AddField(
            model_name='mae',
            name='ibm_personalidade',
            field=models.TextField(blank=True, default='', verbose_name='IBM Personalidade'),
        ),
        migrations.AlterField(
            model_name='mae',
            name='ibm_verificado_mulher',
            field=models.BooleanField(verbose_name='API da IBM verificou se é mulher.'),
        ),
        migrations.AddField(
            model_name='comentariomae',
            name='mae_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mae_destino_comentario', to='mae.Mae'),
        ),
        migrations.AddField(
            model_name='comentariomae',
            name='mae_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mae_origem_comentario', to='mae.Mae'),
        ),
        migrations.AddField(
            model_name='avaliacaomae',
            name='mae_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mae_destino_avaliacao', to='mae.Mae'),
        ),
        migrations.AddField(
            model_name='avaliacaomae',
            name='mae_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mae_origem_avaliacao', to='mae.Mae'),
        ),
        migrations.AddField(
            model_name='apoiomae',
            name='mae_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mae_destino', to='mae.Mae'),
        ),
        migrations.AddField(
            model_name='apoiomae',
            name='mae_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mae_origem', to='mae.Mae'),
        ),
    ]
