# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 01:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1, verbose_name='Sexo')),
                ('crianca_especial', models.BooleanField(verbose_name='É criança com cuidados especiais')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('alergico', models.CharField(blank=True, max_length=250, verbose_name='Alergias')),
                ('doencas', models.TextField(blank=True, verbose_name='Doenças')),
                ('escola', models.CharField(blank=True, max_length=50, verbose_name='Escola')),
                ('cep_escola', models.IntegerField(blank=True, null=True, verbose_name='Cep Escola')),
                ('natacao', models.BooleanField(verbose_name='Faz natação')),
                ('cep_natacao', models.IntegerField(blank=True, null=True, verbose_name='Cep Natação')),
                ('judo', models.BooleanField(verbose_name='Faz judo')),
                ('cep_judo', models.IntegerField(blank=True, null=True, verbose_name='Cep judo')),
                ('bale', models.BooleanField(verbose_name='Faz bale')),
                ('cep_bale', models.IntegerField(blank=True, null=True, verbose_name='Cep bale')),
                ('ingles', models.BooleanField(verbose_name='Faz ingles')),
                ('cep_ingles', models.IntegerField(blank=True, null=True, verbose_name='Cep ingles')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='Mae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome completo')),
                ('facebook_id', models.IntegerField(verbose_name='Facebook ID')),
                ('ibm_verificado_mulher', models.BooleanField(verbose_name='API da IBM verificou se eh mulher.')),
                ('foto_mae_gd', models.ImageField(upload_to='uploads', verbose_name='Foto da Mãe grande')),
                ('foto_mae_pq', models.ImageField(upload_to='uploads', verbose_name='Foto da Mãe Pequena')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cep', models.IntegerField(verbose_name='CEP')),
                ('aceita_crianca_especial', models.BooleanField(verbose_name='Aceita crianças especiais')),
                ('idade_minima_crianca', models.IntegerField(verbose_name='Idade mínima da criança')),
                ('idade_maxima_crianca', models.IntegerField(verbose_name='Idade maxima da criança')),
                ('telefone', models.IntegerField(verbose_name='Telefone')),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor/Hora')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('disponivel_segunda', models.BooleanField(verbose_name='Segunda')),
                ('disponivel_terca', models.BooleanField(verbose_name='Terça')),
                ('disponivel_quarta', models.BooleanField(verbose_name='Quarta')),
                ('disponivel_quinta', models.BooleanField(verbose_name='Quinta')),
                ('disponivel_sexta', models.BooleanField(verbose_name='Sexta')),
                ('disponivel_sabado', models.BooleanField(verbose_name='Sábado')),
                ('disponivel_domingo', models.BooleanField(verbose_name='Domingo')),
                ('disponivel_hora_inicio', models.TimeField(blank=True, verbose_name='Hora inicio')),
                ('disponivel_hora_fim', models.TimeField(blank=True, verbose_name='Hora fim')),
                ('animal_estimacao', models.CharField(choices=[('C', 'Cachorro'), ('G', 'Gato'), ('P', 'Passaro')], max_length=1, verbose_name='Animais de estimação')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(verbose_name='post')),
                ('mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mae.Mae')),
            ],
        ),
        migrations.AddField(
            model_name='imagens',
            name='mae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mae.Mae'),
        ),
        migrations.AddField(
            model_name='friends',
            name='mae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mae.Mae'),
        ),
        migrations.AddField(
            model_name='filho',
            name='mae',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mae.Mae'),
        ),
    ]
